name: contoso-chat-openai-prompty
metadata:
  template: contoso-chat-openai-prompty@0.0.1
hooks:
  postprovision:
    posix:
      shell: sh
      continueOnError: false
      interactive: true
      run: infra/hooks/postprovision.sh
    windows:
      shell: pwsh
      continueOnError: false
      interactive: true
      run: infra/hooks/postprovision.ps1
infra:
    provider: "bicep"

pipeline:
  variables:
    - APPINSIGHTS_CONNECTIONSTRING
    - AZURE_CONTAINER_ENVIRONMENT_NAME
    - AZURE_CONTAINER_REGISTRY_ENDPOINT
    - AZURE_CONTAINER_REGISTRY_NAME
    - AZURE_COSMOS_NAME
    - AZURE_EMBEDDING_NAME
    - AZURE_ENV_NAME
    - AZURE_LOCATION
    - AZURE_OPENAI_API_VERSION
    - AZURE_OPENAI_CHAT_DEPLOYMENT
    - AZURE_OPENAI_ENDPOINT
    - AZURE_OPENAI_NAME
    - AZURE_OPENAI_RESOURCE_GROUP_LOCATION
    - AZURE_OPENAI_RESOURCE_GROUP_LOCATION
    - AZURE_RESOURCE_GROUP
    - AZURE_SEARCH_ENDPOINT
    - AZURE_SEARCH_NAME
    - AZURE_SUBSCRIPTION_ID
    - COSMOS_CONTAINER
    - COSMOS_ENDPOINT
    - OPENAI_TYPE
    - SERVICE_ACA_IMAGE_NAME
    - SERVICE_ACA_NAME
    - SERVICE_ACA_URI

  secrets:
    - BING_SEARCH_KEY
